#!/usr/bin/env ruby

require_relative 'psql'
require_relative 'mysql'

BACKUP_PATH = ENV['BACKUP_PATH'] || Dir.pwd

DBBackup::PostgreSQL.new(
  destination: BACKUP_PATH
).backup

DBBackup::MySQL.new(
  destination: BACKUP_PATH
).backup
